### ISSUE TITLE
transient sessions

### ISSUE THREAD

**Issue by pekeler** [arangodb/foxx-sessions#1]
I'm a little confused why one would want to persist a session in ArangoDB. It seems more complicated compared just having an encrypted user-key in a cookie. My background is Ruby on Rails which has been using this more transient approach by default (there used to be an option to persist the session, but that was removed two years ago because they consider it an anti pattern).

Having just read up on JWT, which allows me to have any kind of payload for the session, and seeing that you're already supporting JWT, I'd like to see a foxx-sessions app that gave me control over the payload (I'd stick the user's key in it) and does away with the overhead of storing/loading the session in the DB.

**Comment by pluma** [comment]
I'm actually using JWT-based sessions in production myself, so I completely see where you're coming from. The truth is that there's simply not much to do if you want to implement JWT-based sessions.

I'll see if I can come up with a strawman implementation and whether this is better solved with an actual app or just a recipe.

**Comment by pluma** [comment]
@pekeler I've added a purely JWT-based sessions app to the Foxx app store [`sessions-jwt`](https://github.com/arangodb/foxx-sessions-jwt) that doesn't use any collections and deprecated the `jwt` option in Foxx `controller.activateSessions` (as it is entirely redundant). It only works in 2.6 but it should otherwise do the trick.

**Comment by pekeler** [comment]
Oh great. Thank you! I'll check it out when 2.6 is available.
